experiment: ex7

# data source
PATH:
  main_vol: /journel/s0/zur74/data/new_energy_well/train_vol/main_vol
  sub_vol: /journel/s0/zur74/data/new_energy_well/train_vol/sub_vol
  sub_vol_large: /journel/s0/zur74/data/new_energy_well/train_vol/sub_vol_large
ct_idx: [2,3,4,5]

# checkpoints directory
checkpoints:
  PATH: /journel/s0/zur74/LatentPoreUpscale3DNet/lpu3dnet/train/checkpoints