
# data source
PATH:
  main_vol: /journel/s0/zur74/data/new_energy_well/train_vol/main_vol
  sub_vol: /journel/s0/zur74/data/new_energy_well/train_vol/sub_vol
  sub_vol_large: /journel/s0/zur74/data/new_energy_well/train_vol/sub_vol_large
  image_tokens: /journel/s0/zur74/data/new_energy_well/train_vol/tokens_6
  image_tokens_cond: /journel/s0/zur74/data/new_energy_well/train_vol/cond_6

ct_idx: [2,3,4,5]
ct_idx_val: [0,1]
# checkpoints directory
checkpoints:
  PATH: /journel/s0/zur74/LatentPoreUpscale3DNet/lpu3dnet/train/checkpoints